version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: temppass
    volumes:
      - mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  weatheralmanac:
    image: weatheralmanac:local
    restart: always
    ports:
      - 8081:8081

volumes:
  mysql: # Creates/uses volume at \data\docker\volumes